name: unit_tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - name: Install dependencies
        run: sudo apt-get install libeigen3-dev
      - uses: actions/checkout@v1
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: make
        run: cd build && make
      - name: Run Test
        run: build/USV_Tests
      - name: Check python setup.py
        run: pip install .
